sudo: required
dist: trusty

language: ruby

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app

env:
  - DB=postgres
  - DB=mysql

script:
  - bundle exec rake test_app
  - bundle exec rake spec

rvm:
  - 2.3.1
  - 2.2.7

branches:
  only:
    - master

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
